-------- Build -------------------------------------------
FROM maven:3.9.6-eclipse-temurin-17 as builder
WORKDIR /build
COPY . .
RUN mvn clean package -DskipTests

---- Runtime ------------------------------------------
FROM eclipse-temurin:17-jre-slim
WORKDIR /app
COPY --from=builder /build/target/*.war app.war
ENTRYPOINT ["java", "-jar", "app.war"]