global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8072']

  # Frontend (Node.js/React avec prom-client)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
        module: [ http_2xx ]
    static_configs:
        - targets: ['front:8072'] # frontend Angular local
    relabel_configs:
        - source_labels: [ __address__ ]
          target_label: __param_target
        - source_labels: [ __param_target ]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter:9115
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['172.26.126.113:8080']

  - job_name: 'node'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]